[package]
name = "rust-csv2beancount"
version = "0.1.0"
authors = ["Alex Kursell <alexkursell@gmail.com>"]
edition = "2018"

[dependencies]
yaml-rust = "0.4"
csv = "1.1.1"
structopt = "0.2"
chrono = "0.4"
